modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="some_mod_idk"
version="1.0.0"
displayName="some mod idk"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ottlo, MCreator"

[[dependencies.some_mod_idk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



